---
title: "Viz&EDA"
author: "Shun Xie"
date: "2022-09-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggridges)
```


```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

Let's make a scatterplot:
```{r}
head(weather_df)

ggplot(weather_df,aes(x=tmin,y = tmax))+geom_point()
```

Make a scatterplot but different
```{r}
weather_df %>%
  drop_na()%>%
  ggplot(aes(x=tmin, y = tmin))+geom_point()
```

Lets keep making the same plot but different. 

```{r}
weather_scatter = weather_df %>%
  drop_na()%>%
  ggplot(aes(x=tmin, y = tmin))

weather_scatter+geom_point()
```

```{r}
weather_df %>%
  ggplot(aes(x=tmin,y=tmax,color = name))+geom_point()
```

```{r}
weather_df %>%
  drop_na()%>%
  ggplot(aes(x=tmin, y = tmax))+geom_point(aes(color = name))+geom_smooth()
```

scatter plot with each name class has the smooth line
```{r}
weather_df %>%
  drop_na()%>%
  ggplot(aes(x=tmin, y = tmax,color=name))+geom_point()+geom_smooth()
```


Make points transparent
```{r}
weather_df %>%
  drop_na()%>%
  ggplot(aes(x=tmin, y = tmax,color=name))+geom_point(alpha=.3)+geom_smooth()
```

Make seperate panels
```{r}
weather_df %>%
  drop_na()%>%
  ggplot(aes(x=tmin, y = tmax,color=name))+
  geom_point(alpha=.3)+
  geom_smooth(se=FALSE)+
  facet_grid(.~name)
#or by row using: facet_grid(name~.)
```

tmax and tmin is boring. Consider other things:

```{r}
weather_df %>%
  ggplot(aes(x=date, y = tmax, color = name))+
  geom_point(aes(size=prcp),alpha=.3)+
  geom_smooth(se=FALSE)+
  facet_grid(.~name)
  #+theme(axis.test.x = element_text(angle =90,vjust=0.5,hjust=1))
```
Some quick stuff
```{r}

weather_df %>%
  ggplot(aes(x= tmax,y = tmin))+
  geom_hex()
```







